version: '3.8'
services:
  mtop_db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mtop_db
    ports:
      - '5437:5432'
    volumes:
      - mtop_db_data:/var/lib/postgresql/data

  mailpit:
    image: axllent/mailpit
    restart: always
    ports:
      - "1025:1025" # SMTP port
      - "8025:8025" # Web UI port
    environment:
      MP_MAX_MESSAGES: 5000

volumes:
  mtop_db_data:
